config/routes.rb
Pinterestforkittens::Application.routes.draw do
  devise_for :users
  resources :pins

  get "/about" => 'page#about'

  root "page#index"
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :description, presence: true
	validates :description, length: { minimum: 5 }
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
    
    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pins_helper.rb
module PinsHelper
  def description_error
    if @pin.errors[:description].size > 0
      return "has-error"
    end

    return ""
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterestforkittens</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Pinterest For Kittens</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Pins", pins_path %></li> 

      <% if user_signed_in? %>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path,method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %> 

    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/page/about.html.erb
<div class="page-header">
  <h1>A epic journey begins <small>these are our baby steps</small></h1>
</div>

<div class="row">
  <div class="col-md-4"><img class="img-responsive" src="http://builds.happyfuncorp.com/Kittens/9.jpg"/></div>
  <div class="col-md-8">
    <h2>These are our baby steps</h2>

    <p>We get a lot of pitches from people who seem to think they are hollywood producers:</p>

    <ul>
      <li>It's like twitter, but for lists</li>
      <li>It's like the yelp of yoga studios</li>
      <li>It's like buzz feed except for movies</li>
      <li>It's like pinterest for donuts</li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <h3>SERIOUSLY, PINTEREST FOR DONUTS</h3>

    <p>So we needed to figure out something that we could build in a few weeks, an idea that would make sense at first glance that we could fill out more or less depending upon how much progress we made.</p>

    <p>Top things that people use the internet for</p>

    <ol>
      <li>Porn</li>
      <li>Pictures of kittens</li>
      <li>??? whatever</li>
    </ol>

    <p>Since #1 didn't seem professional, this is how we settled on pinterest for kittens.</p>
  </div>
  <div class="col-md-4"><img class="img-responsive" src="http://builds.happyfuncorp.com/Kittens/2.jpg"/></div>
  <div class="col-md-4"><img class="img-responsive" src="http://builds.happyfuncorp.com/Kittens/4.jpg"/></div>
</div>

app/views/page/index.html.erb
<div class="jumbotron">
  <h1>We all love kittens</h1>
  <p>But I <i>just don't know</i> where to find them on the <b>internet</b>.</p>
  <p>
    <a class="btn btn-primary btn-lg" role="button" href="/about">Learn more</a>
    <a class="btn btn-danger btn-lg" role="button" href="https://www.google.com/search?q=puppies&tbm=isch">I prefer puppies</a>
  </p>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin, html: { class: "form-horizontal"} ) do |f| %>
  <% if @pin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button class="close" aria-hidden="true" data-dismiss="alert" type="button">&times;</button>

      <h4><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h4>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group <%= description_error %>">
    <%= f.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="actions col-sm-offset-2">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
  <h1>We all love kittens</h1>
  <p>But I <i>just don't know</i> where to find them on the <b>internet</b>.</p>
  <p>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>
<% end %>

<% if user_signed_in? %>
<h4>Why hello, <%= current_user.email %>!</h4>
<% end %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= time_ago_in_words pin.created_at %></td>
        <td><%= pin.user.try( :email ) %></td>
        <% if current_user == pin.user %>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %> 
        <td></td> <td></td> <td></td> 
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Pin', new_pin_path, class: "btn btn-primary btn-lg" %>
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>